app:
  upload:
    dir:
    ip-limit: 5
    max-file-count: 3
    max-file-size: 20
    mime-types:
      - application/x-hwp
      - application/haansofthwp
      # MS Office
      - application/msword # .doc
      - application/vnd.openxmlformats-officedocument.wordprocessingml.document # .docx
      - application/vnd.ms-excel # .xls
      - application/vnd.openxmlformats-officedocument.spreadsheetml.sheet # .xlsx
      - application/vnd.ms-powerpoint # .ppt
      - application/vnd.openxmlformats-officedocument.presentationml.presentation # .pptx
      # Text
      - text/plain
      # Archive
      - application/zip
      - application/x-7z-compressed # .7z
      - application/gzip # .gz
      # Image
      - image/jpeg
      - image/png
      - image/gif
      - image/bmp
      - image/webp
      # Video
      - video/mp4
      - video/webm
      - video/avi # AVI는 표준 MIME 타입이 명확하지 않을 수 있음. 환경에 따라 달라짐.
      - video/mpeg
      # Audio
      - audio/mpeg # .mp3
      - audio/wav # .wav
      - audio/ogg # .ogg
      # PDF
      - application/pdf
    expiration-minutes:
      - 10
      - 60
      - 360
      - 720
      - 1440

  cache:
    linkDetailCache:
      max-size: 15000
    ipCountCache:
      max-size: 10000
